export interface yearOption {
  readonly value: number;
  readonly label: string;
}

export const yearOptions: readonly yearOption[] = [
  { value: 1996, label: "1996" },
  { value: 1997, label: "1997" },
  { value: 1998, label: "1998" },
  { value: 1999, label: "1999" },
  { value: 2000, label: "2000" },
  { value: 2001, label: "2001" },
  { value: 2002, label: "2002" },
  { value: 2003, label: "2003" },
  { value: 2004, label: "2004" },
  { value: 2005, label: "2005" },
  { value: 2006, label: "2006" },
  { value: 2007, label: "2007" },
  { value: 2008, label: "2008" },
  { value: 2009, label: "2009" },
  { value: 2010, label: "2010" },
  { value: 2011, label: "2011" },
  { value: 2012, label: "2012" },
  { value: 2013, label: "2013" },
  { value: 2014, label: "2014" },
  { value: 2015, label: "2015" },
  { value: 2016, label: "2016" },
  { value: 2017, label: "2017" },
  { value: 2018, label: "2018" },
  { value: 2019, label: "2019" },
  { value: 2020, label: "2020" },
  { value: 2021, label: "2021" },
  { value: 2022, label: "2022" },
];

export interface makeOption {
  readonly value: string;
  readonly label: string;
}

export const makeOptions: readonly makeOption[] = [
  { value: "Acura", label: "Acura" },
  { value: "Alfa Romeo", label: "Alfa Romeo" },
  { value: "American Motors", label: "American Motors" },
  { value: "Aston Martin", label: "Aston Martin" },
  { value: "Audi", label: "Audi" },
  { value: "BMW", label: "BMW" },
  { value: "Bentley", label: "Bentley" },
  { value: "Bugatti", label: "Bugatti" },
  { value: "Buick", label: "Buick" },
  { value: "Cadillac", label: "Cadillac" },
  { value: "Chevrolet", label: "Chevrolet" },
  { value: "Chrysler", label: "Chrysler" },
  { value: "Daewoo", label: "Daewoo" },
  { value: "Daihatsu", label: "Daihatsu" },
  { value: "Datsun", label: "Datsun" },
  { value: "DeLorean", label: "DeLorean" },
  { value: "Dodge", label: "Dodge" },
  { value: "Eagle", label: "Eagle" },
  { value: "Ferrari", label: "Ferrari" },
  { value: "FIAT", label: "FIAT" },
  { value: "Fisker", label: "Fisker" },
  { value: "Ford", label: "Ford" },
  { value: "GMC", label: "GMC" },
  { value: "Genesis", label: "Genesis" },
  { value: "Geo", label: "Geo" },
  { value: "Honda", label: "Honda" },
  { value: "HUMMER", label: "HUMMER" },
  { value: "Hyundai", label: "Hyundai" },
  { value: "Infiniti", label: "Infiniti" },
  { value: "Isuzu", label: "Isuzu" },
  { value: "Jaguar", label: "Jaguar" },
  { value: "Jeep", label: "Jeep" },
  { value: "Kia", label: "Kia" },
  { value: "Lamborghini", label: "Lamborghini" },
  { value: "Lancia", label: "Lancia" },
  { value: "Land Rover", label: "Land Rover" },
  { value: "Lexus", label: "Lexus" },
  { value: "Lincoln", label: "Lincoln" },
  { value: "Lotus", label: "Lotus" },
  { value: "Lucid", label: "Lucid" },
  { value: "MG", label: "MG" },
  { value: "Maserati", label: "Maserati" },
  { value: "Maybach", label: "Maybach" },
  { value: "Mazda", label: "Mazda" },
  { value: "McLaren", label: "McLaren" },
  { value: "Mercedes-Benz", label: "Mercedes-Benz" },
  { value: "Mercury", label: "Mercury" },
  { value: "MINI", label: "MINI" },
  { value: "Mitsubishi", label: "Mitsubishi" },
  { value: "Nissan", label: "Nissan" },
  { value: "Noble", label: "Noble" },
  { value: "Oldsmobile", label: "Oldsmobile" },
  { value: "Opel", label: "Opel" },
  { value: "Pagani", label: "Pagani" },
  { value: "Panoz", label: "Panoz" },
  { value: "Peugeot", label: "Peugeot" },
  { value: "Plymouth", label: "Plymouth" },
  { value: "Pontiac", label: "Pontiac" },
  { value: "Porsche", label: "Porsche" },
  { value: "Renault", label: "Renault" },
  { value: "RAM", label: "RAM" },
  { value: "Rolls-Royce", label: "Rolls-Royce" },
  { value: "Roush", label: "Roush" },
  { value: "Saab", label: "Saab" },
  { value: "Saleen", label: "Saleen" },
  { value: "Saturn", label: "Saturn" },
  { value: "Scion", label: "Scion" },
  { value: "Shelby", label: "Shelby" },
  { value: "Smart", label: "Smart" },
  { value: "Spyker", label: "Spyker" },
  { value: "SRT", label: "SRT" },
  { value: "Studebaker", label: "Studebaker" },
  { value: "Subaru", label: "Subaru" },
  { value: "Suzuki", label: "Suzuki" },
  { value: "Tesla", label: "Tesla" },
  { value: "Toyota", label: "Toyota" },
  { value: "Volkswagen", label: "Volkswagen" },
  { value: "Volvo", label: "Volvo" },
];
